[package]
name = "play_with_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.3"
superslice = "1.0.0"
itertools = "0.10.0"
num="0.4.0"